default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20
  timeout: 5000

development:
  <<: *default
  database: your-move_development

test:
  <<: *default
  database: your-move_test

production:
  <<: *default
  database: your-move_production
