default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: your-move_development

test:
  <<: *default
  database: travis_ci_test
  username: postgres

production:
  <<: *default
  database: your-move_production
